version: '3.8'

services:
  frontend:
    build: ./PPMfrontend
    ports:
      - "80:3000"

  backend:
    build: ./PowerPlantMapAPI
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5000
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_URLS=http://+:5000

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ASDfgh123456!%
      - MSSQL_PID=Standard
    volumes:
      - PPM:/var/opt/mssql

volumes:
  PPM:
