version: '3.8'

services:
  frontend:
    build: ./PPMfrontend
    ports:
      - "443:3001"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/:ro

  backend:
    build: ./PowerPlantMapAPI
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_URLS=https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/powerplantmap.tech.pfx
    volumes:
      - /etc/letsencrypt/live/powerplantmap.tech:/https/:ro

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PWD}
      - MSSQL_PID=Standard
    volumes:
      - PPM:/var/opt/mssql

volumes:
  PPM:
