@startuml GetData

(*) --> QueryDataFromTheApi

if "Megvan mindkét időadat?" then
  -->[true]Különbség kiszámítása
  if "Kissebb, mint 24?" then
      -->[true]Adatlekérdezés
  else
    -->[false]Felosztás
    -->QueryDataFromTheApi
  endif
else
  -->[false]Legutolsó lekérdezése
  -->Végidőpont kiszámítása
endif

@enduml