@startuml sequence
actor       Felhasználó as user
entity      Frontend    as fe
entity      Backend     as be
database    Database    as db

user -> fe : Főoldal megnyitása
fe -> be : GetPowerPlantBasics(), GetPowerOfPowerPlants()
be -> db : Lekérdezések
db -> be : Térkép és termelési adatok
be -> fe : Térkép és termelési adatok
fe -> user : Kigenerált térkép és diagramm

user -> fe : Erőmű kiválasztása, erőműnézet megnyitása
fe -> be : GetPowerPlantDetails() az erőművel paraméterben
be -> db : Lekérdezések
db -> be : Erőmű és részletes termelési adatok
be -> fe : Erőmű és részletes termelési adatok
fe -> user : Diagramm

user -> fe : Múltbeli dátum választása
fe -> be : GetPowerOfPowerPlants a dátummal paraméterben
be -> db : Lekérdezés
db -> be : Adatok
be -> fe : Adatok
fe -> user : Diagramm
be -> be : QueryDataFromTheApi() ha nincsenek még meg az akkori adatok
be -> db : Új adatok mentése
be -> db : Lekérdezés
db -> be : Adatok
be -> fe : Adatok
fe -> user : Diagramm
@enduml