name: Build and Test
run-name: Build and Test the app
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
        working-directory: ./PPMfrontend
      - name: Build the app
        run: npm run build
        working-directory: ./PPMfrontend

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.414"
      - name: Change sdk version
        run: dotnet new globaljson --sdk-version 6.0.414 --force && dotnet --version
        working-directory: ./PowerPlantMapAPI
      - name: Show current branch
        run: git branch --show-current
        working-directory: ./PowerPlantMapAPI
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./PowerPlantMapAPI
      - name: Build app
        run: dotnet build
        working-directory: ./PowerPlantMapAPI
        env:
          APPSETTINGS: ${{ secrets.APPSETTINGS }}
      - name: Run tests
        run: dotnet test
        working-directory: ./PowerPlantMapAPI
